### ISSUE TITLE
"start.sh" in RaspberryPi-IoT-Central-1.0.0.zip shows an error and does not work

### ISSUE THREAD

**Issue by keijiinoue** [Microsoft/microsoft-iot-central-firmware#5]
When executing ./start.sh it shows the following error:
--
dpkg-query: package 'libboost-python1.62.0' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libboost-python1.62.0
E: Couldn't find any package by regex 'libboost-python1.62.0'
Traceback (most recent call last):
  File "./main.py", line 22, in <module>
    from iotHub import IotHubClient
  File "/home/pi/Documents/IoT-Central/src/iotHub.py", line 6, in <module>
    import iothub_client
ImportError: libboost_python-py35.so.1.62.0: cannot open shared object file: No such file or directory
--

And I updated start.sh to use libboost-python1.55.0. When executing the updated start.sh it shows the following error:
--
Traceback (most recent call last):
  File "./main.py", line 22, in <module>
    from iotHub import IotHubClient
  File "/home/pi/Documents/IoT-Central/src/iotHub.py", line 6, in <module>
    import iothub_client
ImportError: libboost_python-py35.so.1.62.0: cannot open shared object file: No such file or directory
--

**Comment by keijiinoue** [comment]
This issue has been resolved.
When I use Raspbian "Stretch" version, it worked fine.
